name: image-analysis-23
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - jupytext
  - notebook
  - matplotlib
  - scikit-image=0.20.0
  - jupyter-book=0.15.1
  - pooch==1.7.0
  - scikit-learn==1.2.2

  # napari 0.4.18 dependencies
  - app-model>=0.1.0,<0.3.0
  - appdirs>=1.4.4
  - cachey>=0.2.1
  - certifi>=2020.6.20
  - dask>2.15,!=2.28.0
  - imageio>=2.20,!=2.11.0,!=2.22.1
  - jsonschema>=3.2.0
  - lazy_loader>=0.2
  - magicgui>=0.7
  - napari-console>=0.0.6
  - napari-plugin-engine>=0.1.9
  - napari-svg>=0.1.10
  - npe2>=0.7.0
  - numpy>=1.21
  - numpydoc>=1.5
  - pandas>=2.0
  - pillow!=7.1.0,!=7.1.1
  - pint>=0.17
  - psutil>=5.0
  - psygnal>0.3.4
  - pydantic>1.9.0,<2
  - pygments>=2.6.0
  - pyopengl>=3.1.0
  - pyyaml>=5.1
  - qtpy>=1.10.0
  - scipy>=1.5.4
  - superqt>=0.4.1
  - tifffile>=2020.2.16
  - toolz>=0.10.0
  - tqdm>=4.56.0
  - typing_extensions>=4.2.0
  - vispy>=0.12.1,<0.13
  - wrapt>=1.11.1
  - zarr
  - pyqt >=5.12.3,!=5.15.0
  - pip:
    - napari==0.4.18rc2  # remove when napari 0.4.18 is on conda-forge
    - scikit-image==0.21.0  # remove when skimage 0.21 is on conda-forge
    - napari-animation
